/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
    id("com.google.devtools.ksp")
    id("com.android.library")
}

android {
    namespace = "org.tidepool.sdk"
    compileSdk = 34

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    add("kspCommonMainMetadata", "androidx.room:room-compiler:2.8.1")
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                api(project(":TidepoolKotlinAPI:domain"))
                implementation(project(":TidepoolKotlinAPI:data"))

                implementation("com.squareup.retrofit2:retrofit:3.0.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")

                // Kotlinx.serialization dependencies
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
                implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")

                // OkHttp for MediaType
                implementation("com.squareup.okhttp3:okhttp:5.1.0")

                // Room KMP dependencies
                implementation("androidx.room:room-runtime:2.8.1")
                implementation("androidx.sqlite:sqlite-bundled:2.5.0")

                // Koin dependency injection
                implementation("io.insert-koin:koin-core:4.1.0")
                implementation("io.insert-koin:koin-annotations:2.1.0")
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
                // Koin testing
                implementation("io.insert-koin:koin-test:4.1.0")
            }
        }

        val androidMain by getting
        val androidUnitTest by getting
    }
}